### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by AnyaPizza** [UltimateDoge5/PhantomShapes#1]
The game crashes when trying to open the config screen or when pressing P.

On Minecraft 1.20.1. 

Crash report:

Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_4265.<init>(net.minecraft.class_310, int, int, int, int)'
	at org.pkozak.screen.ShapeListWidget.<init>(ShapeListWidget.kt:16)
	at org.pkozak.screen.ShapesScreen.method_25426(ShapesScreen.kt:21)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at org.pkozak.PhantomShapesClient.onInitializeClient$lambda$2(PhantomShapesClient.kt:78)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$cjb000$fabric-lifecycle-events-v1$onEndTick(class_310.java:11522)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by UltimateDoge5** [comment]
Thanks for the feedback! From what I see, the UI element for rendering lists had its API changed from version `1.20.3`. I'm developing on `1.20.4` and didn't really expect any of these APIs to be different than those in `1.20.0` and assumed my mod would run on the lower versions. This means that, unfortunately, I can't fix this issue as I would have to degrade the whole project.

The only thing I can do is correct the versions on Modrinth. If you'd like to use the mod, your only option is to upgrade to at least `1.20.3`.

**Comment by NanamiPizza** [comment]
> Thanks for the feedback! From what I see, the UI element for rendering lists had its API changed from version `1.20.3`. I'm developing on `1.20.4` and didn't really expect any of these APIs to be different than those in `1.20.0` and assumed my mod would run on the lower versions. This means that, unfortunately, I can't fix this issue as I would have to degrade the whole project.
> 
> The only thing I can do is correct the versions on Modrinth. If you'd like to use the mod, your only option is to upgrade to at least `1.20.3`.

I see, I just started modding recently. Is it possible to downgrade it myself? If so would you be willing to maybe briefly explain how I would go about it? I understand if you would rather not, just wondering if possible.

**Comment by UltimateDoge5** [comment]
> I see, I just started modding recently. Is it possible to downgrade it myself? If so would you be willing to maybe briefly explain how I would go about it? I understand if you would rather not, just wondering if possible.

I'm not so sure how you could do that, my modding adventure also started not so long ago. But on the fabric wiki, there is a [tutorial](https://fabricmc.net/wiki/tutorial:migratemappings) about updating your yarn mappings. The IDE should download all the things for you after changing the gradle properties.

**Comment by NanamiPizza** [comment]
> > I see, I just started modding recently. Is it possible to downgrade it myself? If so would you be willing to maybe briefly explain how I would go about it? I understand if you would rather not, just wondering if possible.
> 
> I'm not so sure how you could do that, my modding adventure also started not so long ago. But on the fabric wiki, there is a [tutorial](https://fabricmc.net/wiki/tutorial:migratemappings) about updating your yarn mappings. The IDE should download all the things for you after changing the gradle properties.

Thank you. I'll look into it. I doubt I'll figure it out but who knows haha. Looks like a really good mod though, can't wait to use it eventually.
